# Generated by Django 5.2.1 on 2025-05-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_course_enrollement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='module',
            new_name='total_chap',
        ),
    ]
