# Generated by Django 5.2.1 on 2025-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_module_course_total_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
